### ISSUE TITLE
Samsung GT-P7310

### ISSUE THREAD

**Issue by KJS1212** [truboxl/termux-packages-altarch#3]
Can this package be used with the Termux app and if so, where should it be extracted? I would love to see Termux working on my Tegra 2 device

**Comment by truboxl** [comment]
Hi @KJS1212

I assume you will use decatf's custom ROM with at least Android 7 since that contains NEON emulation library that will be useful later on. Then install Termux app from F-Droid. You will get an error after install and open the app as expected.

I have added a new tar.gz file which is based on the zip file. It has the symlinks installed and a patched status file that fixes dpkg issue. You can download the tar.gz file since that will be easier to install than the zip file.

I will talk in detail how to use the zip file and tar.gz file and some extra setup later.

~~https://github.com/truboxl/termux-packages-altarch/releases/tag/bootstrap-2022.10.23-r1%2Bapt-android-7~~ EDIT: Hold on need to patch libc++ as well...

Since this bootstrap is a few months old, some stuff will be broken if you install new package or do package upgrade so bear in mind. I am unable to generate new bootstraps as you can see from the latest GitHub Actions result and remain so in the near term. A dedicated repo for arm vfpv3-d16 is the best option in the future.

Feel free to ask questions here.

**Comment by KJS1212** [comment]
To clarify, do I need to enable neon emulation? It uses a lot of battery and makes my device get hot so I'd like to avoid this if at all possible

**Comment by truboxl** [comment]
The bootstrap itself contains the bare minimum packages that are build without Neon.
The moment you start upgrade or install packages from official repo, the installation will break as all the packages in the official repo are built with Neon. You will need the Neon emulation library from this point.

The long term solution is of course rebuilt all packages without Neon and host the packages in a separate repo. But I have no concrete plans yet.

I will try to upload the fixed bootstrap by today or a day or two...

**Comment by truboxl** [comment]
Added the fixed bootstrap tar.gz file at https://github.com/truboxl/termux-packages-altarch/releases/tag/bootstrap-2022.10.23-r1%2Bapt-android-7

Simply download the file and open using Termux
It will save to downloads folder, don't care the error for now
Then open Termux in failsafe session and execute:
```
cd /data/data/com.termux/files
/system/bin/tar xvf /data/data/com.termux/files/home/downloads/bootstrap-arm-vfpv3-d16.tar.gz
```
Exit Termux and open again should work

**Comment by truboxl** [comment]
I will close this issue for now, feel free to contact if there's any issue
